service: nf-processor
org: sasakitecnologia

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: prod
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

package:
  individually: true

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-versions
  - serverless-plugin-log-retention

useDotenv: true

custom:
  logRetentionInDays: 30
  prune:
    automatic: true
    includeLayers: true
    number: 3

functions:
  createInvoice:
    handler: src/server.handler
    events:
      - http:
          path: /invoice
          method: post
          cors:
            origin: '*'
