service: price-friendly-api
org: sasakitecnologia

provider:
  name: aws
  runtime: nodejs20.x
  versionFunctions: false
  stage: prod
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: '*'

package:
  individually: true
  excludeDevDependencies: true

plugins:
  - serverless-dotenv-plugin
  - serverless-prune-versions
  - serverless-plugin-log-retention

useDotenv: true

custom:
  logRetentionInDays: 30
  prune:
    automatic: true
    includeLayers: true
    number: 3

functions: ${file(./src/resources/functions.yml)}

resources: ${file(./src/resources/database.yml)}
